apiVersion: v1
kind: Secret
metadata:
    name: ksops-test
data:
    token: ENC[AES256_GCM,data:kY6exdMLH4YvnfzGzP3kJuXd7S65CIsEz7p3ETyrkNFxJ7sJCKxrDnCHWASv7reNhDJrwDOJR2AhyMgbGukmsCJnhnsbvM8ouS4z16UzpSCfAQTjvjQcpp4hskM38d28EPJ04FVfZ7//yHxpCHO3oPaiqs2V85rAQAxffVckgGZGXQNf7GaTO5k7gMxvvTN92HOQKfmceqLcsnJoBdQmsond2lv4YsP/oJfLwQfd7QIuvA3LAlxmDZKrOyvlwTzKBFfGjD0oHNpZK9tQT3ao9lkF/88R7C86oy0DveHBU5VchEZGdjgb3St/R+oD4h8GDgc03aUnJiiQi9K66jWRYe1coXPVwvCEK9BtiekdfPP5BS+PqdsKeyC/vfC2Q4Efv93zFIUoMVYFEULRxIKGzVIc0NzVSa8bgZIkVR+WhcPtytVGQMTuA0YMcfJitVUX0xdX7E6uoTCD0sUGf19owcuD/Yq4QVMwPAN5LRl2QKhcE7UNKnHQ7A==,iv:4EJa0ZcWC7lvIBARjEebZAT8tLD/dXXZ3GysYfPkz/g=,tag:jdFX4SEEIxfcSV0tMdz4Uw==,type:str]
sops:
    age:
        - recipient: age1x7ngzl8rrxqnkhpvrr7pdkwfl566w7elvf088pln07fgq92074xsafe46z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UWxSRVR1cFNNRkJ2Qktx
            RnFuMWk3eU5XUm14ejZDYUFjL0c4K3Bad0JVCmE4cms1NFdPazNnb2svMGIzUDAr
            RWdtcXhxSHhVd0pHV05UK3QwMDd2MmsKLS0tIE9HaUdybXI4NGRGVkVKamlQMDdW
            NjlxNE9wTUV5L1pUbys3WWczTDFIV28KbwjN5oDbuh+w5LBgtgxx1ecUflBQ9AYq
            vPpmR1XypEnxKsDf0ZndeHTlExR4jdNbONz9PGpIHDz7vcawHfSCCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-21T14:03:22Z"
    mac: ENC[AES256_GCM,data:ahAvd+4mPQ2odrOj4jvQAVs0j/EnYrrPNOZEku6lCXsnpK5wPMJZLD3FQaHwnWCUN7QAicUWushljRDVBiLaobbnSnBmuAptQTz/uPMSbO2eNDX2KebY3eZN5DndrgvStWFwh7DWeVf7PYWS553MntLVWRDIBkQp7mf67KlQbfE=,iv:WU91AZAG58GP1otSMpbwbar/mwwKnAXApn7bhf1EOIs=,tag:UgEsQE3Uv3KZPF61/oHiKQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
