apiVersion: viaductoss.github.com/v1
kind: ksops
metadata:
  name: test-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secret.enc.yaml
